### ISSUE TITLE
how to watch directory changes?

### ISSUE THREAD

**Issue by tonyrewin** [kkl-fe/live-dev-server#4]

**Comment by lceric** [comment]
Now you can use it in v0.10.0

```js
{
  watcher: {
    options: null, // chokidar options
    on: ['add', 'addDir', 'change'], // chokidar on
  },
}
```
In the `inject code`, you will receive `wacher-[name]`, and `isDir` can be used to determine whether it is a folder.
https://github.com/paulmillr/chokidar#api
https://github.com/kkl-fe/live-dev-server#configuration-file

**Comment by tonyrewin** [comment]
Thank you!
